version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homeserve_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Laravel Backend
  backend:
    build: ./back-end
    container_name: laravel_app
    command: php artisan serve --host=0.0.0.0  --port=80
    restart: always
    volumes:
      - ./back-end:/var/www
    depends_on:
      - db
    ports:
      - "9000:80"

  # React Frontend
  frontend:
    build: ./front-end
    container_name: react_app
    restart: always
    volumes:
      - ./front-end:/app
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173

volumes:
  db_data: